package nexus.app.stander;

import java.awt.CardLayout;
import javax.swing.JSplitPane;
import nahon.comm.event.Event;
import nahon.comm.event.EventListener;
import chart.data.CSPData;
import chart.spchart.panel.SpectralChartPane;
import java.util.logging.Level;
import nahon.comm.faultsystem.FaultCenter;
import sps.app.solapp.CollectControl;
import table.std.SPDataTablePane;
import sps.app.solapp.SoildApp;
import sps.app.solapp.data.SolTestData;
import sps.dev.data.SSPData;
import sps.platform.SoildSystem;
import sps.platform.SpectralPlatService;
import table.data.TSPData;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jiche
 */
public class CalSoildCollect extends javax.swing.JPanel {

    public CalSoildCollect() {
        initComponents();

        //初始化表格和曲线
        this.InitTableAndChart();

        //初始化控制器
        this.InitDataAnalyzer();
    }

    // <editor-fold defaultstate="collapsed" desc="初始化表格和曲线"> 
    private SPDataTablePane dataTablePane = new SPDataTablePane();

    private SpectralChartPane dataChartPane = new SpectralChartPane();

    private JSplitPane chartAnddataSplit;

    //初始化表格界面
    private void InitTableAndChart() {
        this.dataTablePane.SetTitle("SpectralDataTable", "Original");

        this.dataChartPane.SetMaxRange(65535, -1000);

        chartAnddataSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, dataChartPane, null);
        chartAnddataSplit.setResizeWeight(1.0);
        /* Init Display Area */
        DisplayArea.setLayout(new CardLayout());
        DisplayArea.add(chartAnddataSplit);
    }

    //刷新表格
    private void UpdateTable(SSPData main) {
        this.dataTablePane.UpdateData(new TSPData(main.waveIndex, main.datavalue));
    }

    //刷新主曲线
    private void UpdateChart(SSPData main) {
        this.dataChartPane.DisplaySPData("main", new CSPData(main.waveIndex, main.datavalue));
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="注册控制器"> 
    private CollectControl appcontrol;

    private void InitDataAnalyzer() {
        this.appcontrol = SoildSystem.GetInstance().GetSoilControl();
//        /* Register to DataSource */
        this.appcontrol.ObsEvent.RegeditListener(new EventListener<SolTestData>() {
            @Override
            public void recevieEvent(final Event<SolTestData> event) {
                DisplayData(event.GetEvent());
//                SwingUtilities.invokeLater(new Runnable() {
//                    @Override
//                    public void run() {
////                        DisplayData(event.GetEvent());
//                    }
//                });
            }
        });
    }

    private void DisplayData(SolTestData data) {
        /* display main data */
        if (data.absorbe_rate == null) {
            this.UpdateTable(data.original_data.data);
            this.UpdateChart(data.original_data.data);
        } else {
            this.UpdateTable(data.absorbe_rate);
            this.UpdateChart(data.absorbe_rate);
            if (!this.appcontrol.GetObsBill().IsBaseN0Enable()) {
                this.Label_N0.setText(data.Nd + "");
            }
            if (!this.appcontrol.GetObsBill().IsBaseP0Enable()) {
                this.Label_P0.setText(data.Pd + "");
            }
            if (!this.appcontrol.GetObsBill().IsBaseK0Enable()) {
                this.Label_K0.setText(data.Kd + "");
            }
        }
    }
    // </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DisplayArea = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        Button_EnableBase = new javax.swing.JToggleButton();
        Button_EnableN0 = new javax.swing.JToggleButton();
        Button_EnableP0 = new javax.swing.JToggleButton();
        Button_EnableK0 = new javax.swing.JToggleButton();
        Label_N0 = new javax.swing.JLabel();
        Label_P0 = new javax.swing.JLabel();
        Label_K0 = new javax.swing.JLabel();
        ToggleButton_KDEnable = new javax.swing.JToggleButton();

        DisplayArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout DisplayAreaLayout = new javax.swing.GroupLayout(DisplayArea);
        DisplayArea.setLayout(DisplayAreaLayout);
        DisplayAreaLayout.setHorizontalGroup(
            DisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        DisplayAreaLayout.setVerticalGroup(
            DisplayAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 346, Short.MAX_VALUE)
        );

        jLabel1.setText("标准氮吸光度:");

        jLabel2.setText("标准磷吸光度:");

        jLabel3.setText("标准钾吸光度:");

        Button_EnableBase.setText("保存标准灯");
        Button_EnableBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EnableBaseActionPerformed(evt);
            }
        });

        Button_EnableN0.setText("保存");
        Button_EnableN0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EnableN0ActionPerformed(evt);
            }
        });

        Button_EnableP0.setText("保存");
        Button_EnableP0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EnableP0ActionPerformed(evt);
            }
        });

        Button_EnableK0.setText("保存");
        Button_EnableK0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_EnableK0ActionPerformed(evt);
            }
        });

        Label_N0.setText("---- %");

        Label_P0.setText("---- %");

        Label_K0.setText("---- %");

        ToggleButton_KDEnable.setText("扣除暗电流");
        ToggleButton_KDEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_KDEnableActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Button_EnableBase, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ToggleButton_KDEnable, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(48, 48, 48)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_K0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_EnableK0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_P0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_EnableP0))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_N0, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_EnableN0)))
                .addContainerGap(192, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button_EnableBase, ToggleButton_KDEnable});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(Button_EnableN0)
                            .addComponent(Label_N0))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Button_EnableP0)
                            .addComponent(Label_P0)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ToggleButton_KDEnable)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Button_EnableBase)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(Button_EnableK0)
                    .addComponent(Label_K0))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(DisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(DisplayArea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ToggleButton_KDEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_KDEnableActionPerformed
        try {
            SpectralPlatService.GetInstance().GetDevManager().GetDevControl().GetDataCollecor().SetDkEnable(ToggleButton_KDEnable.isSelected());
        } catch (Exception ex) {
            FaultCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
        }
    }//GEN-LAST:event_ToggleButton_KDEnableActionPerformed

    private void Button_EnableBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EnableBaseActionPerformed
        SoildSystem.GetInstance().GetSoilControl().SetBaseData(Button_EnableBase.isSelected());
        Button_EnableBase.setSelected(SoildSystem.GetInstance().GetSoilControl().GetObsBill().IsBaseEnable());
    }//GEN-LAST:event_Button_EnableBaseActionPerformed

    private void Button_EnableN0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EnableN0ActionPerformed
        SoildSystem.GetInstance().GetSoilControl().SaveN0Data(Button_EnableN0.isSelected());
        Button_EnableN0.setSelected(SoildSystem.GetInstance().GetSoilControl().GetObsBill().IsBaseN0Enable());
    }//GEN-LAST:event_Button_EnableN0ActionPerformed

    private void Button_EnableP0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EnableP0ActionPerformed
        SoildSystem.GetInstance().GetSoilControl().SaveP0Data(Button_EnableP0.isSelected());
        Button_EnableP0.setSelected(SoildSystem.GetInstance().GetSoilControl().GetObsBill().IsBaseP0Enable());
    }//GEN-LAST:event_Button_EnableP0ActionPerformed

    private void Button_EnableK0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_EnableK0ActionPerformed
        SoildSystem.GetInstance().GetSoilControl().SaveK0Data(Button_EnableK0.isSelected());
        Button_EnableK0.setSelected(SoildSystem.GetInstance().GetSoilControl().GetObsBill().IsBaseK0Enable());
    }//GEN-LAST:event_Button_EnableK0ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JToggleButton Button_EnableBase;
    private javax.swing.JToggleButton Button_EnableK0;
    private javax.swing.JToggleButton Button_EnableN0;
    private javax.swing.JToggleButton Button_EnableP0;
    private javax.swing.JPanel DisplayArea;
    private javax.swing.JLabel Label_K0;
    private javax.swing.JLabel Label_N0;
    private javax.swing.JLabel Label_P0;
    private javax.swing.JToggleButton ToggleButton_KDEnable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
