/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.debug;

import forge.bill.dev.adapter.NahonDevice;
import forge.bill.platform.ForgeSystem;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DebugPane extends javax.swing.JPanel {

    /**
     * Creates new form DebugPane
     */
    public DebugPane() {
        initComponents();
        
        ComboBox_MEM.removeAllItems();
        ComboBox_MEM.addItem(NahonDevice.MEMTYPE.EIA);
        ComboBox_MEM.addItem(NahonDevice.MEMTYPE.VPA);
        ComboBox_MEM.addItem(NahonDevice.MEMTYPE.NVPA);
        ComboBox_MEM.addItem(NahonDevice.MEMTYPE.MDA);
        ComboBox_MEM.addItem(NahonDevice.MEMTYPE.SRA);
        
        this.ComboBox_Type.removeAllItems();
        for(String type : MemoryConvert.GetInputType()){
            ComboBox_Type.addItem(type);
        }
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ComboBox_MEM = new javax.swing.JComboBox();
        MEM_ADDR = new javax.swing.JTextField();
        MEM_LEN = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        InputMem = new javax.swing.JTextArea();
        SET1 = new javax.swing.JButton();
        GET = new javax.swing.JButton();
        ComboBox_Type = new javax.swing.JComboBox();

        ComboBox_MEM.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        MEM_ADDR.setText("2");

        MEM_LEN.setText("4");

        InputMem.setColumns(20);
        InputMem.setRows(5);
        jScrollPane1.setViewportView(InputMem);

        SET1.setText("Set");
        SET1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SET1ActionPerformed(evt);
            }
        });

        GET.setText("Get");
        GET.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GETActionPerformed(evt);
            }
        });

        ComboBox_Type.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ComboBox_MEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MEM_ADDR, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(MEM_LEN, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(ComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                                .addComponent(SET1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(GET, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ComboBox_MEM, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEM_ADDR, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(MEM_LEN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SET1)
                    .addComponent(GET)
                    .addComponent(ComboBox_Type, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(177, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void SET1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SET1ActionPerformed
        try {
            ForgeSystem.GetInstance().devControl.SetMem((NahonDevice.MEMTYPE) ComboBox_MEM.getSelectedItem(),
                Integer.valueOf(MEM_ADDR.getText()), Integer.valueOf(MEM_LEN.getText()),
                MemoryConvert.ConvertMemToByte(this.ComboBox_Type.getSelectedItem().toString(), InputMem.getText()));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SET1ActionPerformed

    private void GETActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GETActionPerformed
        try {
            byte[] value = ForgeSystem.GetInstance().devControl.GetMEM((NahonDevice.MEMTYPE) ComboBox_MEM.getSelectedItem(),
                Integer.valueOf(MEM_ADDR.getText()), Integer.valueOf(MEM_LEN.getText()));

            String output = MemoryConvert.ConvertByteToString(this.ComboBox_Type.getSelectedItem().toString(), value);

            this.InputMem.setText(output);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex);
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_GETActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox ComboBox_MEM;
    private javax.swing.JComboBox ComboBox_Type;
    private javax.swing.JButton GET;
    private javax.swing.JTextArea InputMem;
    private javax.swing.JTextField MEM_ADDR;
    private javax.swing.JTextField MEM_LEN;
    private javax.swing.JButton SET1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
