/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.seteia;

import forge.bill.dev.NahonDevControl;
import forge.form.other.EiaTableModel;
import forge.bill.platform.ForgeSystem;
import javax.swing.JComboBox;
import nahon.drv.data.EquipmentInfo;

/**
 *
 * @author jiche
 */
public class CustomEIASetupPane extends javax.swing.JPanel {

    /**
     * Creates new form UpdateForm
     */
    java.awt.Frame parent = null;

    public CustomEIASetupPane(java.awt.Frame parent) {
        this.parent = parent;

        initComponents();

        initInternalForm();
    }

    private JComboBox devnamelist;

    //初始化内部版本界面
    private void initInternalForm() {
        
    }

    //更新EIA信息
    public void UpdateEIA() {
        EiaTableModel model = new EiaTableModel(ForgeSystem.GetInstance().devControl.GetEquipmentInfo());
        model.EnableEditable(false);
        devEiaTable.setModel(model);
        this.TextField_DevAddr.setText(String.valueOf(ForgeSystem.GetInstance().devControl.GetDevAddr()));
        
    }

    //转换输入的设备地址
    private byte getInputAddr() {
        try {
            return Byte.valueOf(this.TextField_DevAddr.getText());
        } catch (Exception ex) {
            this.TextField_DevAddr.setText("0");
            return (byte) 0;
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        InfoList = new javax.swing.JList();
        DevicePanel = new javax.swing.JPanel();
        Button_Set = new javax.swing.JButton();
        eiaTablePane = new javax.swing.JScrollPane();
        devEiaTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        TextField_DevAddr = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        TextArea_Info = new javax.swing.JTextArea();

        InfoList.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane3.setViewportView(InfoList);

        DevicePanel.setBorder(javax.swing.BorderFactory.createTitledBorder("设备参数修改"));

        Button_Set.setText("设置");
        Button_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SetActionPerformed(evt);
            }
        });

        devEiaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "EIA信息", "值"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        eiaTablePane.setViewportView(devEiaTable);

        jLabel1.setText("原始信息：");

        jLabel2.setText("设备地址：");

        TextField_DevAddr.setText("1");

        TextArea_Info.setColumns(20);
        TextArea_Info.setRows(5);
        jScrollPane1.setViewportView(TextArea_Info);

        javax.swing.GroupLayout DevicePanelLayout = new javax.swing.GroupLayout(DevicePanel);
        DevicePanel.setLayout(DevicePanelLayout);
        DevicePanelLayout.setHorizontalGroup(
            DevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eiaTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(DevicePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addContainerGap(244, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
            .addGroup(DevicePanelLayout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TextField_DevAddr, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Button_Set, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        DevicePanelLayout.setVerticalGroup(
            DevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DevicePanelLayout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eiaTablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(DevicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TextField_DevAddr, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_Set))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 187, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DevicePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(DevicePanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    //下发eia，并且记录出场信息
    private void Button_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SetActionPerformed
        //检查状态
        if (ForgeSystem.GetInstance().devControl.State() == NahonDevControl.ControlState.UPDATE) {
            TextArea_Info.setText("请先等待设备升级完成! \r\n");
            return;
        }

        if (ForgeSystem.GetInstance().devControl.SetDevAddr(this.getInputAddr())) {
            TextArea_Info.setText("设备地址更新成功! \r\n");
        } else {
            TextArea_Info.setText("设备地址更新失败! \r\n");
            return;
        }

        //获取新的eia信息
        //EquipmentInfo neweia = ((EiaTableModel) this.devEiaTable.getModel()).GetEIAInfo();

        //连接状态下才可以下发设备信息和设备地址
        //if (ForgeSystem.GetInstance().devControl.SetEquipmentInfo(neweia)) {
        //    TextArea_Info.setText(TextArea_Info.getText() + "信息设置到设备成功! \r\n"); 
        //} else {
         //   TextArea_Info.setText(TextArea_Info.getText() + "设置EIA失败 \r\n");
       // }
    }//GEN-LAST:event_Button_SetActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Set;
    private javax.swing.JPanel DevicePanel;
    private javax.swing.JList InfoList;
    private javax.swing.JTextArea TextArea_Info;
    private javax.swing.JTextField TextField_DevAddr;
    private javax.swing.JTable devEiaTable;
    private javax.swing.JScrollPane eiaTablePane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
