/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forge.form.seteia;

import forge.bill.eia.builder.EIABuilder;
import static forge.form.other.InitPaneHelper.FilePath;
import java.io.File;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class DBConfig extends javax.swing.JDialog {

    /**
     * Creates new form DevInfoConfig
     */
    public DBConfig(java.awt.Frame parent, boolean modal) {
        super(parent, modal);

        initComponents();
        //居中显示
        setLocationRelativeTo(parent);

//        this.CheckBox_IsServerEnable.setVisible(false);
    }

    private EIABuilder eiaSaver;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Config = new javax.swing.JButton();
        TextField_ServerUrl = new javax.swing.JTextField();
        CheckBox_IsServerEnable = new javax.swing.JCheckBox();
        TextField_user = new javax.swing.JTextField();
        TextField_password = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        path_input = new javax.swing.JTextField();
        Button_SelectFile = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        Button_Config.setText("设置");
        Button_Config.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_ConfigActionPerformed(evt);
            }
        });

        CheckBox_IsServerEnable.setText("使用服务器数据库");
        CheckBox_IsServerEnable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CheckBox_IsServerEnableActionPerformed(evt);
            }
        });

        jLabel1.setText("服务器URL:");

        jLabel2.setText("用户:");

        jLabel3.setText("密码:");

        jTextField1.setEditable(false);
        jTextField1.setText("http://192.168.1.110/phpmyadmin");

        jLabel4.setText("管理页面:");

        jLabel5.setText("文件地址:");

        path_input.setEditable(false);

        Button_SelectFile.setText("...");
        Button_SelectFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SelectFileActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 316, Short.MAX_VALUE)
                        .addComponent(Button_Config, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(TextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                        .addComponent(TextField_password, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_ServerUrl))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CheckBox_IsServerEnable)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(path_input, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Button_SelectFile)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(CheckBox_IsServerEnable)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_ServerUrl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TextField_user, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(TextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(path_input, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SelectFile))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(Button_Config))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Button_ConfigActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_ConfigActionPerformed
        try {
            String url = this.TextField_ServerUrl.getText();
            String user = this.TextField_user.getText();
            String password = this.TextField_password.getText();
            this.eiaSaver.GetServerDB().SetDBConfig(url, user, password);
            this.eiaSaver.GetFileDB().SetConfig(this.path_input.getText());
            this.eiaSaver.EnableServer(this.CheckBox_IsServerEnable.isSelected());
            this.dispose();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }
    }//GEN-LAST:event_Button_ConfigActionPerformed

    private void Button_SelectFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SelectFileActionPerformed
        JFileChooser dialog = new JFileChooser(FilePath);
        dialog.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int result = dialog.showOpenDialog(null);

        if (result == JFileChooser.APPROVE_OPTION) {
            File tmp = dialog.getSelectedFile();
            this.path_input.setText(tmp.getPath());
        }
    }//GEN-LAST:event_Button_SelectFileActionPerformed

    private void CheckBox_IsServerEnableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CheckBox_IsServerEnableActionPerformed
        this.enableText(this.CheckBox_IsServerEnable.isSelected());
    }//GEN-LAST:event_CheckBox_IsServerEnableActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Config;
    private javax.swing.JButton Button_SelectFile;
    private javax.swing.JCheckBox CheckBox_IsServerEnable;
    private javax.swing.JTextField TextField_ServerUrl;
    private javax.swing.JTextField TextField_password;
    private javax.swing.JTextField TextField_user;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField path_input;
    // End of variables declaration//GEN-END:variables

    public void SetDBIntance(EIABuilder eiaSaver) {
        this.eiaSaver = eiaSaver;
        this.CheckBox_IsServerEnable.setSelected(eiaSaver.IsServerEnable());
        this.TextField_ServerUrl.setText(eiaSaver.GetServerDB().ServerDBConnectURL);
        this.TextField_user.setText(eiaSaver.GetServerDB().s_user);
        this.TextField_password.setText(eiaSaver.GetServerDB().s_password);

        this.path_input.setText(eiaSaver.GetFileDB().FileDir);
        
        this.enableText(eiaSaver.IsServerEnable());
    }

    private void enableText(boolean value) {
        this.TextField_ServerUrl.setEnabled(value);
        this.TextField_user.setEnabled(value);
        this.TextField_password.setEnabled(value);
        this.jTextField1.setEnabled(value);
        this.path_input.setEnabled(!value);
        this.Button_SelectFile.setEnabled(!value);
    }
}
