/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.devcie.control.config;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import sps.dev.control.ifs.ISPDevLightControl;
import nahon.comm.faultsystem.FaultCenter;
import nahon.comm.tool.languange.LanguageHelper;

/**
 *
 * @author Administrator
 */
public class Set_Light extends javax.swing.JPanel {

    /**
     * Creates new form LeserLightConfig
     */
    public Set_Light() {
        initComponents();

        this.Label_LeserIR.setText(LanguageHelper.getIntance().GetText("Label_LeserIR"));
        this.Label_LeserType.setText(LanguageHelper.getIntance().GetText("Label_LeserType"));
        this.Button_Set.setText(LanguageHelper.getIntance().GetText("Button_Set"));
    }
    private ISPDevLightControl lightcontrol;

    public void SetCollector(ISPDevLightControl lightcontrol) {
        this.lightcontrol = lightcontrol;
        if (this.lightcontrol != null) {
            try {
                this.TextField_IRInput.setText(String.valueOf(this.lightcontrol.GetLLgihtIr()));
                this.Label_LTypeInput.setText(this.lightcontrol.GetLLgihtType());
            } catch (Exception ex) {
                FaultCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_Set = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        Label_LeserIR = new javax.swing.JLabel();
        Label_LeserType = new javax.swing.JLabel();
        TextField_IRInput = new javax.swing.JTextField();
        Label_LeserIRUnit = new javax.swing.JLabel();
        Label_LTypeInput = new javax.swing.JLabel();

        Button_Set.setText("set");
        Button_Set.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SetActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        Label_LeserIR.setText("jLabel1");

        Label_LeserType.setText("jLabel1");

        TextField_IRInput.setText("0");

        Label_LeserIRUnit.setText("mA(1-1500)");

        Label_LTypeInput.setText("jLabel1");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_LeserIR, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TextField_IRInput, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Label_LeserType, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Label_LTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Label_LeserIRUnit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Label_LeserIR)
                    .addComponent(TextField_IRInput)
                    .addComponent(Label_LeserIRUnit))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Label_LeserType)
                    .addComponent(Label_LTypeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(Button_Set, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_Set))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void Button_SetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SetActionPerformed
        if (this.lightcontrol != null) {
            try {
                this.lightcontrol.SetLLgihtIr(Integer.valueOf(this.TextField_IRInput.getText()));
                JOptionPane.showMessageDialog(this, "设置成功!");
            } catch (Exception ex) {
                FaultCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
            }
        }
    }//GEN-LAST:event_Button_SetActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_Set;
    private javax.swing.JLabel Label_LTypeInput;
    private javax.swing.JLabel Label_LeserIR;
    private javax.swing.JLabel Label_LeserIRUnit;
    private javax.swing.JLabel Label_LeserType;
    private javax.swing.JTextField TextField_IRInput;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
