/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_drv_nahon_usb_LibUSB */

#ifndef _Included_com_drv_nahon_usb_LibUSB
#define _Included_com_drv_nahon_usb_LibUSB
#ifdef __cplusplus
extern "C" {
#endif


/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    USBScanDevImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_USBScanDevImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    OpenUSBImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_OpenUSBImpl
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    USBBulkWriteDataImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_USBBulkWriteDataImpl
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    USBBulkReadDataImpl
 * Signature: (I[BII)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_USBBulkReadDataImpl
  (JNIEnv *, jclass, jint, jbyteArray, jint, jint);

/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    USBCtrlDataImpl
 * Signature: (IIIII[BII)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_USBCtrlDataImpl
  (JNIEnv *, jclass, jint, jint, jint, jint, jint, jbyteArray, jint, jint);

/*
 * Class:     com_drv_nahon_usb_LibUSB
 * Method:    CloseUSBImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_drv_nahon_usb_LibUSB_CloseUSBImpl
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
