/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.app.absorbe;

import chart.data.CSPData;
import chart.spchart.panel.SpectralChartPane;
import java.awt.CardLayout;
import javax.swing.JSplitPane;
import sps.dev.data.SSPData;
import table.data.TSPData;
import table.std.SPDataTablePane;

/**
 *
 * @author Administrator
 */
public class AbsChartTable extends javax.swing.JPanel {
    private String tablename = "ARateTable";
    private String chartname = "ARateTable";
    private String mainlinename = "current";
    
    /**
     * Creates new form AbsChartTable
     */
    public AbsChartTable() {
        initComponents();
        
        this.InitRateDataPane();
    }

    
    // <editor-fold defaultstate="collapsed" desc="Rate Init"> 
    public SPDataTablePane rateTablePane = new SPDataTablePane();

    public SpectralChartPane rateChartPane = new SpectralChartPane();

    private JSplitPane rateSplit;

    private void InitRateDataPane() {
        /* Init table pane */
        this.rateTablePane.SetTitle(tablename, "ARate");

        /* Init chart pane */
        this.rateChartPane.SetTitle(chartname);
        this.rateChartPane.SetMaxRange(10, -10);

        /* Init split pane */
        rateSplit = new JSplitPane(JSplitPane.HORIZONTAL_SPLIT, rateChartPane, null);
        rateSplit.setResizeWeight(1.0);

        /* Init Display Area */
        this.setLayout(new CardLayout());
        this.add(rateSplit);
    }

    public void DisplayRateData(SSPData data) {
        this.rateTablePane.UpdateData(new TSPData(data.waveIndex, data.datavalue));
        this.rateChartPane.DisplaySPData(mainlinename, new CSPData(data.waveIndex, data.datavalue));
    }

    public void SetTableVisible(boolean value) {
        if (value) {
            rateSplit.setRightComponent(rateTablePane);
        } else {
            rateSplit.setRightComponent(null);
        }
    }
    // </editor-fold> 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
