package nexus.app.absorbe;

import java.awt.CardLayout;
import java.io.File;
import java.io.FileOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JSplitPane;
import nahon.comm.event.Event;
import nahon.comm.event.EventListener;
import nahon.comm.faultsystem.FaultCenter;
import chart.data.CSPData;
import chart.spchart.panel.SpectralChartPane;
import javax.swing.JLabel;
import nahon.comm.tool.languange.LanguageHelper;
import nexus.main.compent.FileDialogHelp;
import nexus.main.compent.ImageHelper;
import table.std.SPDataTablePane;
import org.jfree.chart.ChartUtilities;
import sps.app.absorbe.AbsorbeApp;
import sps.app.absorbe.SAbsData;
import sps.app.ora.CommonApp;
import sps.dev.data.SSpectralDataPacket;
import sps.platform.SpectralPlatService;
import table.data.TSPData;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author jiche
 */
public class AbsorbeAppUI extends javax.swing.JPanel {

    public AbsorbeAppUI() {
        initComponents();

        //初始化表格和曲线
        this.InitTableAndChart();

        //初始化控制器
        this.InitDataAnalyzer();
    }

    // <editor-fold defaultstate="collapsed" desc="初始化表格和曲线"> 
    private BaseChartTable baseCTPane = new BaseChartTable();
    private AbsChartTable aRateCTPane = new AbsChartTable();

    private void InitTableAndChart() {
        this.ChartTable_TabbedPane.add(this.baseCTPane);
        this.ChartTable_TabbedPane.add(this.aRateCTPane);

        LanguageHelper.getIntance().EventCenter.RegeditListener(new EventListener() {
            @Override
            public void recevieEvent(Event event) {
                ChartTable_TabbedPane.setTitleAt(0, LanguageHelper.getIntance().GetText("BaseSPPane_Name"));
                ChartTable_TabbedPane.setTitleAt(1, LanguageHelper.getIntance().GetText("AbsorbPane_Name"));
            }
        });
    }
    // </editor-fold>

    // <editor-fold defaultstate="collapsed" desc="注册控制器"> 
    private AbsorbeApp abs_app;

    private void InitDataAnalyzer() {
        this.abs_app = SpectralPlatService.GetInstance().GetAppManager().GetAbsorbeApp();
        /* Register to DataSource */
        this.abs_app.RegisterDataCollectListener(new EventListener<SAbsData>() {
            @Override
            public void recevieEvent(final Event<SAbsData> event) {
                DisplayData(event.GetEvent());
//                SwingUtilities.invokeLater(new Runnable() {
//                    @Override
//                    public void run() {
////                        DisplayData(event.GetEvent());
//                    }
//                });
            }
        });
    }

    private void DisplayData(SAbsData data) {
        /* display main data */
        baseCTPane.DisplayMainData(data.original_data.data);

        if (this.abs_app.IsRefSetup()) {
            this.aRateCTPane.DisplayRateData(data.absorbe_rate);
        }
    }
// </editor-fold>

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Button_SaveImage = new javax.swing.JButton();
        Button_SaveData = new javax.swing.JButton();
        ToggleButton_DataTable = new javax.swing.JToggleButton();
        ToggleButton_EnableBase = new javax.swing.JToggleButton();
        ChartTable_TabbedPane = new javax.swing.JTabbedPane();

        Button_SaveImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/app/resources/bmp_save.png"))); // NOI18N
        Button_SaveImage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveImageActionPerformed(evt);
            }
        });

        Button_SaveData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/app/resources/xls_save.png"))); // NOI18N
        Button_SaveData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SaveDataActionPerformed(evt);
            }
        });

        ToggleButton_DataTable.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/app/resources/datatable.png"))); // NOI18N
        ToggleButton_DataTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_DataTableActionPerformed(evt);
            }
        });

        ToggleButton_EnableBase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/nexus/app/resources/ref.png"))); // NOI18N
        ToggleButton_EnableBase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleButton_EnableBaseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Button_SaveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(Button_SaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ToggleButton_DataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(2, 2, 2)
                .addComponent(ToggleButton_EnableBase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(380, Short.MAX_VALUE))
            .addComponent(ChartTable_TabbedPane)
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Button_SaveData, Button_SaveImage, ToggleButton_DataTable, ToggleButton_EnableBase});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ToggleButton_DataTable, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ToggleButton_EnableBase, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SaveImage, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Button_SaveData, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(2, 2, 2)
                .addComponent(ChartTable_TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {Button_SaveData, Button_SaveImage, ToggleButton_DataTable, ToggleButton_EnableBase});

    }// </editor-fold>//GEN-END:initComponents

    private void Button_SaveImageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveImageActionPerformed
        try {
            File file = FileDialogHelp.GetFilePath(".png");
            if (file != null) {
                try (FileOutputStream bout = new java.io.FileOutputStream(file)) {
                    ChartUtilities.writeBufferedImageAsPNG(bout,
                            ImageHelper.mergeImage(this.baseCTPane.dataChartPane.GetChartPanePNG(),
                                    this.aRateCTPane.rateChartPane.GetChartPanePNG(), false));
                    bout.flush();
                }
            }
        } catch (Exception ex) {
            javax.swing.JOptionPane.showMessageDialog(null, ex);
            Logger.getLogger(AbsorbeAppUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_SaveImageActionPerformed

    private void Button_SaveDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SaveDataActionPerformed
        try {
            File file = FileDialogHelp.GetFilePath(".xls");
            if (file != null) {
                this.abs_app.SaveToExcel(file.getAbsolutePath());
                JOptionPane.showMessageDialog(this, "保存成功!");
            }
        } catch (Exception ex) {
            FaultCenter.Instance().SendFaultReport(Level.SEVERE, "保存记录失败!");
            Logger.getGlobal().log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_Button_SaveDataActionPerformed

    private void ToggleButton_DataTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_DataTableActionPerformed
        this.baseCTPane.SetTableVisible(ToggleButton_DataTable.isSelected());
        this.aRateCTPane.SetTableVisible(ToggleButton_DataTable.isSelected());
    }//GEN-LAST:event_ToggleButton_DataTableActionPerformed

    private void ToggleButton_EnableBaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleButton_EnableBaseActionPerformed
        this.abs_app.EnableRefLight(ToggleButton_EnableBase.isSelected());
        this.ToggleButton_EnableBase.setSelected(this.abs_app.IsRefSetup());
        if (this.abs_app.IsRefSetup()) {
            baseCTPane.DisplayBaseData(this.abs_app.GetBaseData().data);
        } else {
            baseCTPane.DisplayBaseData(null);
        }
    }//GEN-LAST:event_ToggleButton_EnableBaseActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_SaveData;
    private javax.swing.JButton Button_SaveImage;
    private javax.swing.JTabbedPane ChartTable_TabbedPane;
    private javax.swing.JToggleButton ToggleButton_DataTable;
    private javax.swing.JToggleButton ToggleButton_EnableBase;
    // End of variables declaration//GEN-END:variables

}
