/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class USBDriver_USBLib */

#ifndef _Included_USBDriver_USBLib
#define _Included_USBDriver_USBLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     USBDriver_USBLib
 * Method:    USBScanDevImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_USBScanDevImpl
  (JNIEnv *, jclass, jint NeedInit);

/*
 * Class:     USBDriver_USBLib
 * Method:    OpenUSBImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_OpenUSBImpl
  (JNIEnv *, jclass, jint DevIndex);

/*
 * Class:     USBDriver_USBLib
 * Method:    USBBulkWriteDataImpl
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_USBBulkWriteDataImpl
  (JNIEnv * env, jclass cl, jint nBoardID, jbyteArray sendBuffer, jint len, jint waittime);

/*
 * Class:     USBDriver_USBLib
 * Method:    USBBulkReadDataImpl
 * Signature: (II[BII)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_USBBulkReadDataImpl
  (JNIEnv * env, jclass cl, jint nBoardID, jbyteArray recBuffer, jint len, jint waittime);

/*
 * Class:     USBDriver_USBLib
 * Method:    USBCtrlDataImpl
 * Signature: (IIIII[BII)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_USBCtrlDataImpl
  (JNIEnv * env, jclass cl, jint nBoardID, jint requesttype, jint request,
  jint value, jint index, jbyteArray reqBuffer, jint size, jint waittime);

/*
 * Class:     USBDriver_USBLib
 * Method:    CloseUSBImpl
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_USBDriver_USBLib_CloseUSBImpl
  (JNIEnv *, jclass, jint DevIndex);

#ifdef __cplusplus
}
#endif
#endif
