/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package nexus.devcie.control.config;

import java.awt.Frame;
import nahon.comm.tool.languange.LanguageHelper;
import sps.dev.control.ifs.ISPDevControl;
import sps.dev.control.ifs.ISPDevControl.CSTATE;
import sps.platform.SpectralPlatService;

/**
 *
 * @author jiche
 */
public class DeviceParSetDialog extends javax.swing.JDialog {

    private ISPDevControl devcontrol;

    /**
     * Creates new form SpectralParameterPanel1
     */
    public DeviceParSetDialog() {
        super((Frame) null, true);
        initComponents();
        
        //居中显示
        this.setLocationRelativeTo(null);
        
        this.devcontrol = SpectralPlatService.GetInstance().GetDevManager().GetDevControl();

        if (this.devcontrol.GetControlState() != CSTATE.CLOSE) {
            Set_WavePar spPane = new Set_WavePar();
            spPane.SetCollector(devcontrol.GetSPDevConfig());
            TabbedPane.add(LanguageHelper.getIntance().GetText("SPSetPanel"), spPane);
            
            LinearParSet linearpane = new LinearParSet();
            linearpane.SetCollector(devcontrol.GetSPDevConfig());
            TabbedPane.add(LanguageHelper.getIntance().GetText("LinearPane"), linearpane);
            
//            LightParameterPanel lightpane = new LightParameterPanel();
//            lightpane.SetCollector(devcontrol.GetLightControl());
//            TabbedPane.add(LanguageHelper.getIntance().GetText("lightPane"), lightpane);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TabbedPane = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(TabbedPane, javax.swing.GroupLayout.DEFAULT_SIZE, 271, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TabbedPane;
    // End of variables declaration//GEN-END:variables
}
