/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package nexus.devcie.control.config;

import java.util.logging.Level;
import javax.swing.JOptionPane;
import nahon.comm.faultsystem.FaultCenter;
import nahon.comm.tool.languange.LanguageHelper;
import sps.dev.control.ifs.ISPDevConfig;
import sps.dev.data.SSWaveCaculatePar;

/**
 *
 * @author Administrator
 */
public class Set_WavePar extends javax.swing.JPanel {

    /**
     * Creates new form SPSetPanel
     */
    public Set_WavePar() {
        initComponents();       
        
        this.Button_SetSWPara.setText(LanguageHelper.getIntance().GetText("Button_Set"));
    }
    
    private ISPDevConfig devconfig;
    public void SetCollector(ISPDevConfig config){
        try {
            this.devconfig = config;
            this.SpectralParaTable.setModel(new Set_WaveTable(this.devconfig.GetWaveParameter()));
            
            this.SpectralParaTable.putClientProperty("terminateEditOnFocusLost", Boolean.TRUE);            
        } catch (Exception ex) {
            FaultCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        SpectralParaTable = new javax.swing.JTable();
        Button_SetSWPara = new javax.swing.JButton();

        SpectralParaTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jScrollPane1.setViewportView(SpectralParaTable);

        Button_SetSWPara.setText("Set");
        Button_SetSWPara.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Button_SetSWParaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Button_SetSWPara, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 234, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Button_SetSWPara))
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void SetCParameter() {
//        if (this.SpectralParaTable.isEditing()) {
//            this.SpectralParaTable.getCellEditor().stopCellEditing();
//        }

        SSWaveCaculatePar tmp = new SSWaveCaculatePar();
        Set_WaveTable tmpmdl = (Set_WaveTable) this.SpectralParaTable.getModel();

        tmp.C0 = tmpmdl.parcValue[0];
        tmp.C1 = tmpmdl.parcValue[1];
        tmp.C2 = tmpmdl.parcValue[2];
        tmp.C3 = tmpmdl.parcValue[3];

        try {
            this.devconfig.SetWaveParameter(tmp);
            JOptionPane.showMessageDialog(this, "设置成功!");
        } catch (Exception ex) {
            FaultCenter.Instance().SendFaultReport(Level.SEVERE, ex.getMessage());
        }
    }
    
    private void Button_SetSWParaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Button_SetSWParaActionPerformed
        SetCParameter();
    }//GEN-LAST:event_Button_SetSWParaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Button_SetSWPara;
    private javax.swing.JTable SpectralParaTable;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
